#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/k8s-hardway

- block:
  - name: Step 01 Download k8s components 
    include_tasks: 01.download_components.yml
  tags: [ download_component ]
    
- block:
  - name: Step 02 Setup dns
    include_tasks: 02.setup_dns.yml
  tags: [ setup_dns ]

- block:
  - name: Step 03 Config certiticates
    include_tasks: 03.config_certs.yml
  tags: [ config_certs ]

- block:
  - name: Step 04 Config kubeconfig file
    include_tasks: 04.config_kubeconfig.yml
  tags: [ config_kubeconfig ]

- block:
  - name: Step 05 Config encryption
    include_tasks: 05.config_encryption.yml
  tags: [ config_encryption ]

- block:
  - name: Step 06 Bootstrapping etcd cluster
    include_tasks: 06.bootstrap_etcd_cluster.yml
  tags: [ bootstrap_etcd_cluster ]
  when: inventory_hostname in groups['k8s-master']

- block:
  - name: Step 07 Bootstrapping k8s controllers
    include_tasks: 07.bootstrap_controller.yml
  tags: [ bootstrap_controller ]
  when: inventory_hostname in groups['k8s-master']
