#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/k8s-hardway

arch: amd64
components_url:
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kubectl
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kube-apiserver
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kube-controller-manager
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kube-scheduler
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kube-proxy
  - https://dl.k8s.io/v1.32.3/bin/linux/{{ arch }}/kubelet
  - https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.32.0/crictl-v1.32.0-linux-{{ arch }}.tar.gz
  - https://github.com/opencontainers/runc/releases/download/v1.3.0-rc.1/runc.{{ arch }}
  - https://github.com/containernetworking/plugins/releases/download/v1.6.2/cni-plugins-linux-{{ arch }}-v1.6.2.tgz
  - https://github.com/containerd/containerd/releases/download/v2.1.0-beta.0/containerd-2.1.0-beta.0-linux-{{ arch }}.tar.gz
  - https://github.com/etcd-io/etcd/releases/download/v3.6.0-rc.3/etcd-v3.6.0-rc.3-linux-{{ arch }}.tar.gz

certs:
  core_components:
    - admin
    - kube-proxy
    - kube-scheduler
    - kube-controller-manager
    - kube-api-server
    - service-accounts
  nodes:
    - node-0
    - node-1

encryption_key_directory: "{{ role_path }}/files/encryption"
encryption_key_path: "{{ encryption_key_directory }}/encryption.key"

